spring:
  application:
    name: gateway-zuul-reg-exp
server:
  port: 7772
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true

