server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## 安全认证的配置(SpringBoot2.0之前的配置)
#security:
#  basic:
#    enabled: true
#  user:
#    name: wolf  # 用户名
#    password: abc123   # 用户密码