server:
  port: 6662
spring:
  application:
    name: consumer-user-fegin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zf?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:154518499@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#为Fegin添加日志־
logging:
  level:
    com.toprs.consumeruserfeign.fegin.UserFeginClient: DEBUG
hystrix:
  metrics:
    polling-interval-ms:

