spring:
  application:
    name: gateway-zuul
server:
  port: 7771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

zuul:
  routes:
    abc: #随便写,唯一的就可以
      path: /user/**
      serviceId : provider-user
ribbon:
  eureka:
    enabled: false
provider-user: #这是ribbon要请求的微服务的serviceId
  ribbon:
      listOfServers: http://localhost:1110,http://localhost:1111


#ribbon不使用eureka负载均衡


