spring:
  application:
    name: gateway-zuul
server:
  port: 7771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api  #访问路径添加前缀 http://localhost:7771/api/provider-user/user/getUser/14 映射到http://localhost:7771/provider-user/user/getUser/14
  #strip-prefix: false 默认为true 当值为false时 http://localhost:7771/api/provider-user/user/getUser/14 映射到http://localhost:7771/api/provider-user/user/getUser/14
logging:
  level:
   com.netflix: debug


