spring:
  application:
    name: gateway-zuul
server:
  port: 7771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/,http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true
zuul:
  sensitive-headers:
logging:
  level:
   com.netflix: debug


